services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5278:5278"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5278
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

