FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /backend

COPY . ./
RUN dotnet restore backend.csproj

RUN dotnet publish backend.csproj -c release -o /backend-build --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

WORKDIR /backend
COPY --from=build /backend-build .

EXPOSE 5278
ENTRYPOINT [ "dotnet", "backend.dll" ]